spring.application.name=backend

#Datos BD - I
spring.datasource.url=jdbc:postgresql://localhost:5432/fynansis
spring.datasource.username=postgres
spring.datasource.password=Root.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Datos BD - F
